// <auto-generated />
namespace Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class updateDescrCol : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(updateDescrCol));
        
        string IMigrationMetadata.Id
        {
            get { return "201409091247568_updateDescrCol"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
