// <auto-generated />
namespace Portal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-beta1-30515")]
    public sealed partial class moduleremoveimgBase64 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(moduleremoveimgBase64));
        
        string IMigrationMetadata.Id
        {
            get { return "201406261156146_module-remove-imgBase64"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
